### ISSUE TITLE
no field or method SliceScan

### ISSUE THREAD

**Issue by fils** [StabbyCutyou/sqltocsv#1] opened 2016-05-23 23:08 UTC
Hi,
  I am getting an error:  

```
./main.go:93: results.SliceScan undefined (type *sqlx.Rows has no field or method SliceScan)
```

I am basically just trying to copy what you have in your code and seeing if I can make it work for me.   I keep getting told there is no method SliceScan.  Still, this seems to be how all the code examples are working.   Any guidance is appreciated!

GIST:  https://gist.github.com/fils/42b512d8646a7cdbf3eb9686e42d25e2

**Comment by StabbyCutyou** [comment] 2016-08-13 03:01
Sorry for not noticing this for so long.

Make sure your copy of sqlx in your GOPATH is up to date. Pass the -u flag to `go get` to update it.

**Comment by StabbyCutyou** [comment] 2016-08-16 15:41
Also, reviewing your gist, it seems as though you're just copying my code and putting it somewhere else? I'd have to imagine a better approach here would be to work on an oracle adapter for the code.

If you see this PR: https://github.com/StabbyCutyou/sqltocsv/pull/2

You can see the approach i'm moving toward to make supporting new DBs easier.

**Comment by StabbyCutyou** [comment] 2016-10-06 20:40
Since I have been unable to reproduce this, and have not received any updates from you on the issue, I'm going to close it for now.

If you want to still get help with this issue, please open another issue.

**Closed as completed by StabbyCutyou** 2016-10-06 20:40 UTC
